### ISSUE TITLE
A little bit of help to start

### ISSUE THREAD

**Issue by darmach** [wulkanat/EDDX52#2]
First of all I'd like to congratulate you on a great job! You made a lot of x52 Pro users very happy.

However I am having a hard times getting this to work with EDDiscovery the way I'd like.
Could you provide some examples of Action files which would:
1. turn on all leds let's say Amber color on Elite game start (or EDDiscovery start)
2. Blink certain led (FireB for ex.) red when hardpoints are deployed (I found UI HardpointsDeployed event, but failed to create conditional for this)
3. Blink Fire E button green when FSD charging (before and afterwards it should stay li orange)
4. Turn off all leds on Game shutdown.

Would such setup be possible

**Comment by Theaninova** [comment]
Well, for turning on all LEDs at the game start, you will actually have to call each function one after another and iteratively turn them all on. No way around that. EDDiscovery should provide an action that is being called on game start.
So either you call
`DLLCall EDDX52 setLED, [LED Name], YELLOW`
Or you use
`DLLCall EDDX52 advSetLED, [LED ID], 1`
The download includes a Documentation.txt with all the information.

Blink certain LED when Hardpoints are deployed
Again, EDDiscovery provides these functions. So maby ask there. If you want to know the command to Blink FireB red, you can call
`DLLCall EDDX52 advSetLED, 3, 1, 1, 1, 1, 0`
That should give a uniform 1s on 1s off blink. Basically it is
`avSetLED, ID, State, Number of repeats, Repeat Offset, Flash Duration, Flash Offset`
You can create a "Flash Flash Pause Flash Flash Pause..." for example with
`DLLCall EDDX52 advSetLED, 3, 2, 1, 1, 1, 1`
This gives you `1s on, 1s off, 1s on, 1s off, 1s off`
You can also create Dual Tone Blinking, because you access the individual LED colors, so red and green (Amber is just the combination of both). So if we take our previous Blink Pattern:
`DLLCall EDDX52 advSetLED, 3, 1, 1, 1, 1, 0`
And also call
`DLLCall EDDX52 advSetLED, 4, 1`
We get a uniform Amber Red Amber Red flashing pattern.
By using multiple patterns, you can get really creative there, however, because of the nature of how they work, they will, after some time, get out of sync.
There are two functions to help you with that. One resets all flash pattern timers at once, but they will eventually get out of sync again.
`DLLCall EDDX52 syncFlashPatterns`
The other one makes two flash patterns use the same timer variable. That means, that the Pattern with the lowes time will win and reset to beginning. Just use an Offset there.
`DLLCall EDDX52 permaSyncTo, [LED ID, whiches variable will be used], [LED ID to sync]`
You can break these links with
`DLLCall EDDX52 [LED ID]`

So a setup as you described would be prefectly possible. It is just a matter of what EDDiscovery provides you.
If you have any further questions, I am happy to help you out, you can contact me on Discord: `wulkanat#9653`

**Comment by darmach** [comment]
I think I might've phrased my problem wrong - i don't have a problem with using EDDX52 per se .) But I have a problem with creating logic in EDDiscovery that would trigger DLLCall on specific event:
- landing gear down / up (state)
- hardpoints deployed / retracted (hardpoints state)

I don't know how to create proper conditionals, found UIHardpoints even but don't know how to use it.

**Comment by daniel-finger** [comment]
You can start with an actionScript like this:
```
EVENT UIHardpointsDeployed, UIHardpointsDeployed, "", Condition AlwaysTrue

PROGRAM UIHardpointsDeployed

If EventClass_Deployed IsTrue
    DLLCall EDDX52, setLED, FIRE, ON
Else 
    DLLCall EDDX52, setLED, FIRE, OFF

END PROGRAM
```
But this also lights the Button if scanning something with the discovery scanner. I haven't found a solution for this yet
